version: '3.8'

services:
  zookeeper:
    image: zookeeper:latest
    ports:
      - "2181:2181"
    healthcheck:
      test: ["CMD-SHELL", "echo ruok | nc localhost 2181 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres1:
    image: postgres:latest
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres1_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: postgres -c MAX_PREPARED_TRANSACTIONS=0

  postgres2:
    image: postgres:latest
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - postgres2_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: postgres -c MAX_PREPARED_TRANSACTIONS=0

  postgres3:
    image: postgres:latest
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5434:5432"
    volumes:
      - postgres3_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: postgres -c MAX_PREPARED_TRANSACTIONS=0

  app:
    build: .
    depends_on:
      zookeeper:
        condition: service_healthy
      postgres1:
        condition: service_started
      postgres2:
        condition: service_started
      postgres3:
        condition: service_started
    environment:
      - APP_ZOOKEEPER_HOST=zookeeper:2181
      - APP_POSTGRES_HOSTS=postgres1:5432,postgres2:5432,postgres3:5432
    ports:
      - "5000:5000"

volumes:
  postgres1_data:
  postgres2_data:
  postgres3_data:

networks:
  default:
    name: app_network